name: "Nader's Workshop"
favicon: null
layout_spectrum: 0.6838361141271889
typography_spectrum: 0.4293127243872732
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5758514404296875
  lightness: 0.7195777508895844
  saturation: 0.07718159700743854
  rhythmicContrast: 0.7345276940613985
purpose: []
