name: "Nader's Workshop"
favicon: null
layout_spectrum: 0.75031
typography_spectrum: 0.73625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d030e'
    - '#8b8084'
    - '#a8aba4'
    - '#f7f7f9'
    - '#404a56'
  brandStrength: 0.5
  lightness: 0.7195777508895844
  saturation: 0.1875
  rhythmicContrast: 0.7345276940613985
purpose: []
